Implement Camera Handler
MissouriMRDT/Autonomy_Software pull request #125
Opened 2023-09-16 22:42 UTC by ClayJay3

- Created base camera class for consistency between current and future types of cameras.
- Implemented BasicCam class for standard USB cameras.
- Implemented ZEDCam class for ZED cameras.
- Both camera classes utilize the AutonomyThread class for speedy frame retrieval and copying.
- Created basic CameraHandler for global access of cameras.

Merging camera-handler and creating new issues for GPS fusion and SimCam. This way other project that require cameras can get underway.

Closes #110

2023-09-17 00:37 UTC, ClayJay3 commented
Working on building and pushing new docker images, and fixing the clang and build issues. Don't know why they spontaneously broke.

2023-09-20 05:05 UTC, Byrdman32 requested changes

2023-09-20 05:05 UTC, Byrdman32 commented on .devcontainer/devcontainer.json
> +    "image": "ghcr.io/missourimrdt/autonomy-jetpack:latest",
This needs to be changed to using `ghcr.io/missourimrdt/autonomy-focal:latest` as the enabled one before merging with development.

2023-09-20 05:05 UTC, Byrdman32 commented on .devcontainer/devcontainer.json
> +    //     //     "dockerfile": "Dockerfile_JetPack"
Extra comment symbol needs to be removed before merge.

2023-09-20 05:05 UTC, Byrdman32 commented on CMakeLists.txt
> +## Package Executable // FIXME: Install doesn't work.
Remove `// FIXME: Install doesn't work.` since it has been fixed.

2023-09-20 05:05 UTC, Byrdman32 commented on CMakeLists.txt
> +    add_executable(${PROJECT_NAME}_UnitTests ${UnitTests_SRC})
This line simplification should happen for integration tests too.

2023-09-20 05:05 UTC, Byrdman32 commented on src/AutonomyConstants.h
> +    // Drive constants.
Use consistent headers for constants. Either `// Drive constants` needs to change to look like the
```
    ///////////////////////////////////////////////////////////////////////////
    //// Camera Constants.
    ///////////////////////////////////////////////////////////////////////////
```

or vise versa.

2023-09-20 05:05 UTC, Byrdman32 commented on src/AutonomyGlobals.h
> +// CameraHandler.
Use consistent comment blocks. Either switch `// Versioning:` and `// Board Interfaces:` to look the same as `// CameraHandler.` Or Vise Versa.

2023-09-20 05:05 UTC, Byrdman32 commented on src/drivers/NavigationBoard.h
> +#ifndef NAVIGATIONBOARD_H
Add blank line between header block and first line of code.

2023-09-20 05:05 UTC, Byrdman32 commented on src/interfaces/AutonomyThread.hpp
> +#ifndef AUTONOMYTHREAD_H
Add blank line between header block and first line of code.

2023-09-20 05:05 UTC, Byrdman32 commented on src/interfaces/Camera.hpp
> +///////////////////////////////////////////////////////////////////////////////
Why is this here?

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Check if the camera was successfully opened.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Submit logger message.
Add Blank Line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Check if the frame copy queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +            // Wait for thread pool to finish.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +            // Release lock on frame copy queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Copy frame to data container.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +        // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Append frame fetch container to the scedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.h
> +        // Basic camera specific.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/BasicCam.h
> +
Remove blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Check if the camera was successfully opened.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Submit logger message.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Call generalized update method of zed api.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Check if new frame was computed successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +                // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +                // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +                    // Check that the regular frame was retrieved successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Check if the frame copy queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Wait for thread pool to finish.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Release lock on frame copy queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Get frame container out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Aqcuire mutex for getting frames out of the pose queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Copy pose.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Aqcuire mutex for getting frames out of the pose queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Get IMU linear acceleration.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Repackage angles and accels into vector.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Aqcuire mutex for getting frames out of the pose queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Make copy of object vector. (Apparently the assignement operator actually does a deep copy)
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Aqcuire mutex for getting frames out of the pose queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Check if the queue is empty.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Pop out of queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Make copy of object vector. (Apparently the assignement operator actually does a deep copy)
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Use the condition variable to notify other waiting threads that this thread is finished.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Assemble container.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Assemble container.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Return unsuccessful.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Return unsuccessful.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Return unsuccessful.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +            // Image was not written successfully.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Wait up to 10 seconds for the condition variable to be notified.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Append frame fetch container to the schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock on the frame schedule queue.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Enable object detection.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Give batch params to detection params.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Disable spatial mapping.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Enable spatial mapping.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Reset the positional tracking location of the camera.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // This will reset position and coordinate frame.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Disable pose tracking.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Enable pose tracking and store return code.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Reboot this camera and return the status code.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Release lock.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Give the custom box data to the zed api.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        // Repackage object corner data.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // Reset the positional tracking location of the camera.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +    // This will reset position and coordinate frame.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +            // Sleep for 2ms.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +            // Sleep for 2ms.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +    // Test that the returned average makes sense.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +    // Test that the returned minimum makes sense.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +    // Test that the returned maximum makes sense.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +    // Test that the returned 1% low makes sense.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on tests/Unit/src/util/IPS.cc
> +    // Point to null.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
>           * @date 2023-0723
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
>           * @date 2023-0725
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
>           * @date 2023-0722
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
>           * @date 2023-0725
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenBasicCam.hpp
> + * @date 2023-0722
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> + * @date 2023-0722
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> +            // Check if spatial mapping is enabled.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> +            // Download memory from gpu mats if necessary.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> +    // Declare FPS counter.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> +    // Check if we should turn on spatial mapping.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on examples/vision/OpenZEDCam.hpp
> +    // Turn on ZED features.
Add blank line here for readability.

2023-09-20 05:05 UTC, Byrdman32 commented on src/interfaces/AutonomyThread.hpp
Doxygen blocks need to be using `YYYY-MM-DD` instead of `YYYY-MMDD`.

2023-09-20 20:29 UTC, ClayJay3 commented on .devcontainer/devcontainer.json
> +    //     //     "dockerfile": "Dockerfile_JetPack"
Removed the comment for Dockerfile_Focal only. That way if the build block is uncommentted, "dockerfile" won't be define three times.

2023-09-20 20:35 UTC, ClayJay3 commented on examples/threading/ArucoGenerateTags.hpp
>           * @date 2023-0723
I think these were generated before the date format change happened, so I'll have to go through and manually redo the dates. Done.

2023-09-20 20:58 UTC, ClayJay3 commented on src/interfaces/Camera.hpp
> +///////////////////////////////////////////////////////////////////////////////
It's an enum used by classes that inherit the Camera.hpp interface and is used for many things. Either to simply denote what the pixel layout of the camera is for convenience or to aid in the camera threadpool code to signal what type of frame the FrameFetchContainer is carrying. 

It is physically located at the top of the file and defined outside of the class so that any other class or file can simply include this one and directly reference PIXEL_FORMATS::eBGRA instead of Camera::PIXEL_FORMATS::eBGRA. I didn't place this enum within the AutonomyGlobals.cpp because I wanted to keep the Camera.hpp file simple. Moving this into AutonomyGlobals and then including it from the Camera.hpp file would bring in all things from AutonomyGlobals, and I think it would actually lead to a circular include anyways as AutonomyGlobal indirectly includes Camera.hpp from the ThreadedCameraHandler class.

Doing it this way still makes the enum available through AutonomyGlobals when included and keeps the number of Camera.hpp file includes to a minimum, so I believe this to be the best place to put the PIXEL_FORMATS enum.

2023-09-20 21:03 UTC, ClayJay3 commented on src/vision/cameras/BasicCam.cpp
> +    // Check if the camera was successfully opened.
When writing code, I bunch together different sections, calls, or logic that relate to each other. In this case, the IF statement is simply there to do a simple check/log based on the line directly before it, so I didn't put a new line in between.

The same applies for all the code I write. I think splitting up the code too much can make it less readable.

In this case, I just simplified it a deleted the line after double checking the docs for the VideoCapture.open() method lol.

2023-09-20 21:20 UTC, ClayJay3 commented on src/vision/cameras/BasicCam.h
> +        // Basic camera specific.
Reworked comments for both ZEDCam.h and BasicCam.h

It was originally spaced odd because intellisense kept using the one-line comment in the header file instead of the actual method doc in the .cpp file. For example, when creating a new BasicCam, intellisense would show `Declare public methods and member variables` instead of showing the normal description, parameters, and return info.

2023-09-20 22:14 UTC, Byrdman32 approved these changes

2023-09-20 22:21 UTC, Byrdman32 commented on src/interfaces/Camera.hpp
> +///////////////////////////////////////////////////////////////////////////////
My question was about the `///////////////////////////////////////////////////////////////////////////////`

2023-09-20 22:22 UTC, Byrdman32 approved these changes

2023-09-20 22:23 UTC, Byrdman32 approved these changes

2023-09-20 22:55 UTC, merged