Implement Basic ArUco Vision Detection System #67
MissouriMRDT/Autonomy_Software pull request #140
Opened 2023-10-19 04:02 UTC by ClayJay3

- Adds arucotag namespace for image preprocessing, detection, overlay, and pose estimation.
- Adds tensorflowtag namespace for YOLOv8 detection of tag objects. (Only basic structure for now, will be implemented in #69)
- Adds TagDetector class for mutithreaded, modular tag detection. Easily create new detectors for each camera with this class.
- Adds appropriate handlers for creating tag detectors for cameras.

Closes #67

2023-10-19 16:21 UTC, Byrdman32 requested changes
Overall looks good. A few minor things to change.

2023-10-19 16:21 UTC, Byrdman32 commented on CMakeLists.txt
> +file(GLOB_RECURSE Logging_SRC			  	    CONFIGURE_DEPENDS  "src/AutonomyLogging.cpp")
Since we are only looking for one file here, I would change this from `GLOB_RECURSE` to `GLOB`.

Also, make sure to get the `CONFIGURE_DEPENDS` to line up.

2023-10-19 16:21 UTC, Byrdman32 commented on examples/vision/tagdetection/ArucoDetection.hpp
> +    ZEDCam* ExampleBasicCam1 = globals::g_pCameraHandler->GetZED(CameraHandler::eHeadMainCam);
Why is an object of type `ZEDCam` being given a name with "BasicCam" included?

2023-10-19 16:21 UTC, Byrdman32 commented on src/handlers/TagDetectionHandler.cpp
> +    // Initialize detector for main ZEDcam.
Original: `// Initialize detector for main ZEDcam.`

Recommended Fix: `// Initialize detector for main ZEDCam.`

2023-10-19 16:21 UTC, Byrdman32 commented on src/util/vision/ImageOperations.hpp
> +     * @todo Test this!
Does this still need to be tested?

2023-10-19 16:21 UTC, Byrdman32 commented on src/vision/aruco/ArucoDetection.hpp
> +#ifndef ARUCO_DETECTION_H
Original:
```
#ifndef ARUCO_DETECTION_H
#define ARUCO_DETECTION_H
```

Proposed Fix:
```
#ifndef ARUCO_DETECTION_HPP
#define ARUCO_DETECTION_HPP
```

2023-10-19 16:21 UTC, Byrdman32 commented on src/vision/aruco/ArucoDetection.hpp
> + * @author jspencerpittman (jspencerpittman@gmail.com), clayjay3 (claytonraycowen@gmail.com)
Add: `Kai Shafe (kasq5m@umsystem.edu)` to `@author`

2023-10-19 16:21 UTC, Byrdman32 commented on src/vision/aruco/TagDetector.cpp
> + * @author clayjay3 (claytonraycowen@gmail.com)
Add `jspencerpittman (jspencerpittman@gmail.com)` to `@author`

2023-10-19 16:21 UTC, Byrdman32 commented on src/vision/aruco/TensorflowDetection.hpp
> + * @author clayjay3 (claytonraycowen@gmail.com)
Add `jspencerpittman (jspencerpittman@gmail.com)` to `@author`

2023-10-19 16:21 UTC, Byrdman32 commented on tests/Unit/src/aruco/README.md
The README either needs to be written or removed.

2023-10-19 16:21 UTC, Byrdman32 commented on tests/Unit/src/aruco/rsc/Images.md
All the images within the project are stored in the `data` directory.

Create a directory named `TESTS` in the `data` directory and then put a directory named `aruco` within that. This README can be moved there.

2023-10-19 16:21 UTC, Byrdman32 commented on tests/Unit/src/aruco/rsc/cleanArucoMarker0.png
All the images within the project are stored in the `data` directory.

Create a directory named `TESTS` in the `data` directory and then put a directory named `aruco` within that. This Image can be moved there.

2023-10-19 16:21 UTC, Byrdman32 commented on tests/Unit/src/aruco/rsc/cleanArucoMarkersMultiple.png
All the images within the project are stored in the `data` directory.

Create a directory named `TESTS` in the `data` directory and then put a directory named `aruco` within that. This Image can be moved there.

2023-10-20 02:52 UTC, ClayJay3 commented on src/util/vision/ImageOperations.hpp
> +     * @todo Test this!
Keeping function, @Kai-Shafe might rewrite or improve speed in the future.

2023-10-20 03:36 UTC, Byrdman32 approved these changes

2023-10-20 03:36 UTC, merged