State Machine Overhall
MissouriMRDT/Autonomy_Software pull request #157
Opened 2024-01-17 23:45 UTC by Byrdman32

When the State Machine was initially written we were considering using the boost framework due to it already having some of the state machine and networking needs written for us. However we quickly realized that wasn't going to be a good idea because of the overhead created by boost and some of the methods not being written the best way. This PR is a complete rewrite of our state machine that is based partially off of the old Python one with some needed improvements.

- [x] Create Abstract State Class
  - [x] Constructor
  - [x] Destructor
  - [x] TriggerEvent
  - [x] Run
  - [x] GetState
  - [x] ToString
  - [x] operator==
  - [x] operator!=
  - [x] Start
  - [x] Exit
- [x] Create State Objects (* = New State)
  - [x] Approaching Marker
  - [x] Approaching Object*
  - [x] Avoidance
  - [x] Idle
  - [x] Navigating
  - [x] Reversing
  - [x] Search Pattern
  - [x] Stuck
  - [x] Verifying Marker*
  - [x] Verifying Object*
- [x] Create State Machine Handler from Autonomy Thread Class

Future Improvements:
- [ ] Write Run Methods for each State
- [ ] Create Custom State Logging Level
- [ ] Add RoveComm Commands

2024-01-18 18:43 UTC, ClayJay3 requested changes
Looks great! Left comments on mostly small things. There is one comment that proposes a potential improvement to the State.hpp interface that should improve abstraction and remove the need for a ToString() override in each state class.

2024-01-18 18:43 UTC, ClayJay3 commented on CONTRIBUTING.md
> +- Unordered Map > `um` > Example: `std::unordered_map<int, int> umExampleUseOfUnorderedMap`
Remove std namespace to remain consistent with other examples, or add namespace where necessary.

2024-01-18 18:43 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    enum class States
This enum should probably go withing the State.hpp interface to keep it within proper scope. Putting this inside the State.hpp should still let anything that uses the state machine access it, since the file will inherently include a state, state handler, or autonomy globals.

2024-01-18 18:43 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    enum class States
Also in this case naming conflicts with the States enum are unlikely so you can probably remove the 'class' keyword after moving it to the State.hpp file. But if you want to force the use of the Sates:: scope within the states class then leaving it is fine. Up to you.

2024-01-18 18:43 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    enum class Event
This enum should probably go withing the State.hpp interface to keep it within proper scope. Putting this inside the State.hpp should still let anything that uses the state machine access it, since the file will inherently include a state, state handler, or autonomy globals.

Also in this case naming conflicts with the Event enum are unlikely so you can probably remove the 'class' keyword after moving it to the State.hpp file. But if you want to force the use of the Events:: scope within the states class then leaving it is fine. Up to you.

2024-01-18 18:43 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    inline std::string StateToString(States eState)
No functions inside of AutonomyConstants. Since each of the states has their own toString is this function needed anymore? It isn't being referenced anywhere.

2024-01-18 18:43 UTC, ClayJay3 commented on src/AutonomyGlobals.h
> +
Add your name as author to the globals namespace lol.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
> +namespace statemachine
Remove namespace from handlers.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
> +        if (m_bInitialized && !m_bSwitchingStates && !m_bExiting)
Consider adding comment explain what this if statement is doing.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
> +        SaveCurrentState();
This is sick.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +namespace statemachine
Remove namespace from handlers.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
> +        auto it = umExitedStates.find(eNextState);
Is the auto keyword necessary here? Explicitly defining type like this will be clearer:

std::unordered_map<constants::States, std::shared_ptr<statemachine::State>>::iterator itState = umExitedStates.find(eNextState);

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
> +        return pPreviousState ? pPreviousState->GetState() : constants::States::Idle;
Add comment explaining why the ternary is necessary.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +    class StateMachineHandler : AutonomyThread<void>
Class need documentation.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +            /******************************************************************************
Remove docs from header file to keep it clean, docs are already defined in the .cpp file.

2024-01-18 18:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +namespace statemachine
Namespace needs documentation.

2024-01-18 18:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +#include "../AutonomyConstants.h"
Remove constants and logging includes after other changes.

2024-01-18 18:43 UTC, ClayJay3 commented on src/main.cpp
> +        globals::g_pStateMachineHandler = new statemachine::StateMachineHandler();
Remove statemachine namespace.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingMarkerState.hpp
> +namespace statemachine
Namespace needs documentation.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingMarkerState.hpp
> +    class ApproachingMarkerState : public State
Class needs documentation.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingMarkerState.hpp
> +                return;
Remove return statement for cleanliness.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingObjectState.hpp
> +namespace statemachine
Namespace needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingObjectState.hpp
> +    class ApproachingObjectState : public State
Class needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ApproachingObjectState.hpp
> +                return;
Remove return statement for cleanliness.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/AvoidanceState.hpp
> +namespace statemachine
Needs namespace docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/AvoidanceState.hpp
> +    class AvoidanceState : public State
Class needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/AvoidanceState.hpp
> +            std::vector<double> m_vRoverXPath;
Nice to see these are still around, there's a better/cleaner way to do this though, but that can be done at a later time. If we could still output an image or something of the rovers path that would help a lot during testing.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/IdleState.hpp
> +namespace statemachine
Needs namespace docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/IdleState.hpp
> +    class IdleState : public State
Needs class docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/NavigatingState.hpp
> +namespace statemachine
Needs namespace docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/NavigatingState.hpp
> +    class NavigatingState : public State
Needs class docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ReversingState.hpp
> +namespace statemachine
Needs namespace docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ReversingState.hpp
> +    class ReversingState : public State
Needs class docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/ReversingState.hpp
> +            ReversingState() : State()
POTENTIAL IMPROVEMENT: Add a m_szStateName to State.hpp and add a parameter to the State() constructor (const std::string szStateName = "UNKNOWN"). That will remove the need to reimplement the ToString() method for every state since the default State will just return the give state string.

Then change each states constructor to be like this:
ReversingState() : State("Reverseing")

This would apply for all states and should improve abstraction?

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/SearchPatternState.hpp
> +namespace statemachine
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/SearchPatternState.hpp
> +    class SearchPatternState : public State
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/StuckState.hpp
> +namespace statemachine
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/StuckState.hpp
> +    class StuckState : public State
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/VerifyingMarkerState.hpp
> +namespace statemachine
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/VerifyingMarkerState.hpp
> +    class VerifyingMarkerState : public State
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/VerifyingObjectState.hpp
> +namespace statemachine
Needs docs.

2024-01-18 18:43 UTC, ClayJay3 commented on src/states/VerifyingObjectState.hpp
> +    class VerifyingObjectState : public State
Needs docs.

2024-01-18 18:46 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    inline std::string StateToString(States eState)
If you make the ToString for the state public then this can be removed.

2024-01-18 22:05 UTC, Byrdman32 commented on src/AutonomyConstants.h
> +    inline std::string StateToString(States eState)
I moved this the the States.hpp file because I couldn't think of a way to not need this function since I use this to tell what state we are transitioning to so that object doesn't exist yet.

If you have an idea for how to eliminate this let me know.

2024-01-18 22:08 UTC, Byrdman32 commented on src/interfaces/State.hpp
> +#include "../AutonomyConstants.h"
Why would I remove logging?

2024-01-18 22:14 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +#include "../AutonomyConstants.h"
I didn't see any logging statements in the file at the time, but if you're including it there so you can use it in the other state files instead of individually including it in each state file then that's probably fine to leave it.

2024-01-18 22:43 UTC, ClayJay3 requested changes
Requested small changes on the State constructor and I saw another way to improve abstraction which I didn't catch before, that's my bad.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +    inline std::string StateToString(States eState)
This function needs documentation.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +    enum class States
Put a single line comment explaining enum.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +    enum class Event
Single line comment explaining enum.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
>              State() { Start(); }
This constructor overload can be removed since it does the same thing as the one below, but risks leaving the m_szStateName member variable uninitialized.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +            State(const std::string szStateName = "UNKNOWN")
Constructor needs documentation.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +    enum class Event
Also move this enum above the function.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +            virtual States GetState() const = 0;
I didn't think about this last time, sorry. I think the abstraction can be even further improved by not making this a virtual function and instead handling the implementation in State.hpp.
- Create new private m_eThisState (or better name)
- In the constructor, instead of taking in a string take in a State enum and assign it to member variable.
- Also in constructor, use your StateToString function to assign the m_szStateName member variable.
- Finally in GetState() return m_eThisState.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> +            virtual States GetState() const = 0;
This should also make inheriting the State interface more straightforward, since people won't be able to just give arbitrary names for any new state. They'll have to add an enum first, which will be constant project wide in the statemachine namespace.

2024-01-18 22:43 UTC, ClayJay3 commented on src/interfaces/State.hpp
> -            virtual std::string ToString() const { return typeid(*this).name(); }
This is just a note: the typeid(*this).name() is probably what was causing the weird logging output in some cases. This method of getting the class name returns an odd mangled string.

2024-01-18 23:05 UTC, Byrdman32 commented on src/interfaces/State.hpp
> -            virtual std::string ToString() const { return typeid(*this).name(); }
Yea, I left it though to know when it was having issues. And forgot to remove it.

2024-01-18 23:27 UTC, ClayJay3 approved these changes

2024-01-19 01:23 UTC, Kai-Shafe commented
Looks great to me! I'm a bit confused about the double vectors in AvoidanceState.hpp (m_vRoverXPath, m_vRoverYPath, etc.) and what they're encoding and how that plays into navigation for the state machine.

2024-01-19 02:06 UTC, ClayJay3 commented
> Looks great to me! I'm a bit confused about the double vectors in AvoidanceState.hpp (m_vRoverXPath, m_vRoverYPath, etc.) and what they're encoding and how that plays into navigation for the state machine.

Those vectors are remnants from the old codebase. They were basically there to keep track of the rovers odometry and generate a graph of the path the rover was following and where the rover actually was. I wrote the python code that this was translated from and having multiple lists like this is not very good design and could definitely be done in a more efficient way. But that's for a future PR.

2024-01-19 02:10 UTC, merged

2024-01-19 02:15 UTC, Kai-Shafe reviewed
Looks like we've got our work cut out for us, tysm @Byrdman32.