[HOTFIX] Add missing quotes to dokcer builder
MissouriMRDT/Autonomy_Software pull request #168
Opened 2024-01-27 21:04 UTC by Byrdman32

2024-01-28 02:41 UTC, ClayJay3 approved these changes, later dismissed

2024-01-30 16:00 UTC, ClayJay3 requested changes

2024-01-30 16:00 UTC, ClayJay3 commented on tools/package-builders/quill/quill-arm64-pkg.sh
> +    -D CMAKE_INSTALL_PREFIX=/tmp/pkg/quill_${QUILL_VERSION}_arm64/usr/local ..
Add -D CMAKE_BUILD_TYPE=Release for consistency.

2024-01-31 02:17 UTC, ClayJay3 commented on tools/package-builders/quill/quill-arm64-pkg.sh
> +    -D CMAKE_INSTALL_PREFIX=/tmp/pkg/quill_${QUILL_VERSION}_arm64/usr/local ..
No build type for this one?

2024-01-31 03:04 UTC, Byrdman32 commented on tools/package-builders/quill/quill-arm64-pkg.sh
> +    -D CMAKE_INSTALL_PREFIX=/tmp/pkg/quill_${QUILL_VERSION}_arm64/usr/local ..
The commit didn't get pushed for some reason.

2024-01-31 03:19 UTC, ClayJay3 approved these changes

2024-01-31 03:31 UTC, merged