Add Tensorflow and PyTorch Libraries
MissouriMRDT/Autonomy_Software pull request #180
Opened 2024-02-08 23:42 UTC by ClayJay3

2024-02-27 03:22 UTC, ClayJay3 commented on src/util/vision/YOLOModel.hpp
> +                        std::vector<uint8_t> vInputData(m_cvFrame.data, m_cvFrame.data + (m_cvFrame.cols * m_cvFrame.rows * m_cvFrame.elemSize()));
![](https://media.tenor.com/qxIw6ndszIUAAAAM/abell46s-reface.gif)

2024-03-21 21:00 UTC, Byrdman32 requested changes
Overall looks good, I did notice that we are using the `auto` type in a lot of places throughout the codebase and have noted all the locations throughout this PR but will fix the remaining locations throughout the code through a different PR.

2024-03-21 21:00 UTC, Byrdman32 commented on .devcontainer/Dockerfile_Jammy
> -    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev tzdata curl net-tools \
Why are we getting rid of curl? It's used in the package installer scripts.

2024-03-21 21:00 UTC, Byrdman32 commented on .devcontainer/Dockerfile_JetPack
> -    libdc1394-22-dev libeigen3-dev libglew-dev libgstreamer-plugins-base1.0-dev udev curl net-tools \
Why are we getting rid of curl? It's used in our install scripts.

2024-03-21 21:00 UTC, Byrdman32 commented on examples/vision/cameras/OpenZEDCam.hpp
> +        // std::this_thread::sleep_for(std::chrono::seconds(1));
Why do we have this commented out sleep command?

2024-03-21 21:00 UTC, Byrdman32 commented on src/vision/cameras/ZEDCam.cpp
> +        auto tmStartTime = std::chrono::high_resolution_clock::now().time_since_epoch();
Don't use auto type.

2024-03-21 21:00 UTC, Byrdman32 commented on tools/action-runners/docker-compose.yml
> +        RUNNER_VERSION: 'latest'
`latest` doesn't work when I try to create runners. If you want to use latest some more work might be required.

2024-03-21 21:00 UTC, Byrdman32 commented on tools/action-runners/docker-compose.yml
> +        RUNNER_VERSION: 'latest'
`latest` doesn't work when I try to create runners. If you want to use latest some more work might be required.

2024-03-21 21:00 UTC, Byrdman32 commented on tools/action-runners/docker-compose.yml
> +        RUNNER_VERSION: 'latest'
Current is `2.314.1`

2024-03-21 21:00 UTC, Byrdman32 commented on tools/action-runners/docker-compose.yml
> +        RUNNER_VERSION: 'latest'
Current is `2.314.1`

2024-03-21 21:00 UTC, Byrdman32 commented on tools/action-runners/scripts/start.sh
I don't think we are using this anymore but not sure.

2024-03-21 21:00 UTC, Byrdman32 commented on src/vision/objects/ObjectDetector.cpp
> +    // this->UpdateDetectedObjects(vNewlyDetectedObjects);
Is this needed?

2024-03-22 01:41 UTC, ClayJay3 commented on .devcontainer/Dockerfile_Jammy
> -    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev tzdata curl net-tools \
Curl is already installed in the base image. It also gets reinstalled in the Dockerfiles for the package runners. So I removed it as cleanup.

2024-03-22 01:42 UTC, ClayJay3 commented on src/vision/cameras/ZEDCam.cpp
> +        auto tmStartTime = std::chrono::high_resolution_clock::now().time_since_epoch();
I went through the project and removed all instances of auto and replaced them with proper types where possible.

2024-03-22 01:52 UTC, ClayJay3 commented on src/vision/objects/ObjectDetector.cpp
> +    // this->UpdateDetectedObjects(vNewlyDetectedObjects);
Added TODO for clarity, This will be added in the future.

2024-03-22 01:53 UTC, ClayJay3 commented on tools/action-runners/scripts/start.sh
This doesn't exist on my end, not sure why this is still here.

2024-03-22 01:54 UTC, ClayJay3 commented on examples/vision/cameras/OpenZEDCam.hpp
> +        // std::this_thread::sleep_for(std::chrono::seconds(1));
Removed old line used for debugging.

2024-03-22 02:00 UTC, Byrdman32 approved these changes

2024-03-22 02:01 UTC, Byrdman32 commented on .devcontainer/devcontainer.json
> -    "image": "ghcr.io/missourimrdt/autonomy-jammy:latest",
And this needs to be set to latest once we have a working image

2024-03-22 02:04 UTC, ClayJay3 commented on .devcontainer/devcontainer.json
> -    "image": "ghcr.io/missourimrdt/autonomy-jammy:latest",
I went ahead and set it to latest, all latest images should be working once the actions finish.

2024-03-22 15:37 UTC, merged