Closed Topic/#144
MissouriMRDT/Autonomy_Software pull request #182
Opened 2024-02-16 00:10 UTC by Kai-Shafe

- [ ] NodeGreaterThan functor for std::*_heap functions.
- [ ] AStar Obstacle struct for easy obstacle data storage.
- [ ] Clear Obstacle Data method.
- [ ] Update Obstacle Data method.
- [ ] Add Obstacle method.

- [ ] Plan Avoidance Route method.
    - [ ] Find Nearest Boundary Point helper method.
    - [ ] Round UTMCoordinate helper method.
    - [ ] UTMCoordinate to string helper method for unordered maps.
    - [ ] Valid Coordinate helper method.
    - [ ] Calculate node H value
    - [ ] Construct path method

The primary ASTAR algorithm is located in the Plan Avoidance Route method, and utilizes many helper functions to simplify the code in the method. The algorithm is implemented with additional unordered maps for the AStar nodes that are used to lookup nodes based on their location in constant time. This implementation is memory inefficient, but more computationally efficient than searching the open and closed lists.

The current implementation depends on pulling the next waypoint from the waypoint handler class to determine the destination coordinate to navigate to.

Future Improvements:

- Build a visualizer for testing.

2024-02-16 03:11 UTC, ClayJay3 requested changes
Looks good, but could use some reworking as far as structuring goes. You can keep the existing code just move it around when possible.

I'm surprised the compiler is able to figure stuff out since there are two AStar.h files, need to find a way to merge the two into one file and class.

2024-02-16 03:11 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    const double ASTAR_SQRT_NODE_SIZE       = M_SQRT1_2;    // Square root of m_dNodeSize
Add `// ASTAR config.` comment to further separate these constants since we will have more algorithms in the future. 

Structure similar to camera constants.

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/AStar.h
> +};
Why does this file exist? There is already an ASTAR.h file inside of the src/algorithms/planners directory.

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/Node.h
> +#endif
The concept of a node class for planners functions similar to a utility and a struct would probably be more appropriate (and are often times cleaner). Use the AStarNode struct inside of the util/planners/Nodes.hpp file instead. This is where future node structs for other planners will also be defined.

Remove this file and modify the existing AStarNode struct to suite your needs. Also notice that the member variables are public so you don't need to write getters and setters in the case of a the AStarNode struct.

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> + * @author clayjay3 (claytonraycowen@gmail.com)
Add your name before mine.

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/planners/AStar.h
> +            void FindNearestBoundaryPoint(const geoops::UTMCoordinate& stGoalCoordinate);
Thank you for putting & on the parameters. 😃

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +    };
I don't think a functor is the best way to do this, I believe this breaks encapsulation as well. I haven't worked with functors at all, but if you simply want a way to compare if a node is greater than another, you should overload the `operator>` method by adding a method to the AStarNode struct instead of putting this in the AStar class itself.

2024-02-16 03:11 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +    };
I would also recommend overloading the <, <=, and >= operators as well.

Which would let you directly compare nodes instead of calling a function.

```
nodes::AStarNode stNode1, stNode2;

// Initialize nodes with data.

// Compare nodes.
if (stNode1 > stNode2)
    // Do something cool here.
```

2024-02-16 05:11 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +    };
When I was looking into how I could use std templates for implementing a min-heap, the only way to get std::make_heap to construct a min-heap is to either overload the < operator with the functionality of the > operator (gross) or to pass it a functor that it can use instead. I couldn't find any easier way to do this. A previous version I was working with required a heap, but this version could probably use a priority queue instead. Unfortunately priority queues suffer from the same problem as heaps, only being implemented as a max queue as default and requiring a functor. I'll do some more research and try to come up with something, and I'm very open to ideas.

2024-02-16 05:38 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.h
> +            void FindNearestBoundaryPoint(const geoops::UTMCoordinate& stGoalCoordinate);
Gotta save memory where you can :)

2024-02-16 16:37 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +    };
So after looking at it more, the third parameter of std::make_heap is the comparison operator, and if you omit it, the default comparison operator std::less is used for creating a max heap. However, an std::greater also exists and is a functor.

```
std::greater simply calls the greater than operator for the passed in values, like this:
template <typename T = void>
struct greater {
    constexpr bool operator()(const T& x, const T& y) const {
        return x > y;
    }
};
```

So if you overload the operator> in the AStarNode struct like you have already done. Then you can use std::greater instead of defining and implementing a new functor and greater than will simply invoke your overloaded functions.

So it would look like this.
`std::make_heap(vOpenList.begin(), vOpenList.end(), std::greater<nodes::AStarNode>());`

2024-02-16 22:14 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +    };
Gotcha, I had looked into using std::greater, but I didn't know how to utilize it (combining it with operator overloading is what  I was missing). The change has been made and a new commit has been pushed.

2024-02-16 23:39 UTC, ClayJay3 requested changes

2024-02-16 23:39 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +                {
Extra set of brackets

2024-02-16 23:39 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +        WaypointHandler::Waypoint stGoalWaypoint = globals::g_pWaypointHandler->PeekNextWaypoint();
Instead of reaching out to the navboard and waypoint handler to get the current waypoint and start waypoint, take these UTMCoordinates in as parameters for this method. The current implementation greatly limits the classes functionality since the user can't decide the start and end point. Taking these in as parameters will let you generate paths for areas the rover isn't currently in and will also free up a call to the navboard. (Whatever the current state is will likely make its own call to get the current position anyways, so it's better to let the state pass in the start position)

Always abstract.

2024-02-16 23:39 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +        return m_vPathCoordinates;
Maybe add some new lines in between some of this code, it's pretty bunched together.

2024-02-16 23:39 UTC, ClayJay3 commented on src/util/planners/Nodes.hpp
> +                bool operator>=(const AStarNode& other) const { return this->dKf >= other.dKf; }
Each of these needs it's own docs in order for doxygen to pick it up.

2024-02-16 23:39 UTC, ClayJay3 commented on src/util/planners/Nodes.hpp
> +
Remove newline here.

2024-02-17 03:59 UTC, Byrdman32 requested changes

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> + * @author Kai Shafe (kasq5m@umsystem.edu)
Instead of adding an additional `@author` line just combine it like this:

```/******************************************************************************
 * @brief Main program file. Sets up classes and runs main program functions.
 *
 * @file main.cpp
 * @author Eli Byrd (edbgkk@mst.edu), ClayJay3 (claytonraycowen@gmail.com)
 * @date 2023-06-20
 *
 * @copyright Copyright Mars Rover Design Team 2023 - All Rights Reserved
 ******************************************************************************/```

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> +     * @todo Test me!
Is the `@todo Test me!` still required?

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> +     * @date 2024-02-015
Remove extra 0 from date.

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> +     * @todo This should provide unique strings within our operation scope without having to
Is this `@todo` still required?

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> +     * @todo Test me!
Is this `@todo` still required?

2024-02-17 03:59 UTC, Byrdman32 commented on src/algorithms/planners/AStar.h
> +     * @todo Make Obstacle into struct for readability.
Is this `@todo` still required?

2024-02-17 17:18 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +     * @todo This should provide unique strings within our operation scope without having to
I did not check with @ClayJay3 since he was not at the last meeting, but I did run it by you and got the go ahead.

2024-02-17 17:45 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +        WaypointHandler::Waypoint stGoalWaypoint = globals::g_pWaypointHandler->PeekNextWaypoint();
Gotcha, I was just getting ahead of myself and was only thinking of this in the context of obstacle avoidance. I have changed the PlanAvoidanceRoute() method to take in 2 UTMCoordinates as a start and goal points with the latest commit.

2024-02-17 17:45 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +     * @todo Test me!
Yes, it indicates that I have yet to validate the algorithm with real data coming from the rover as I have made some assumptions about UTMCoordinates that I would like to validate. I have altered the todo to be more specific with what I want to test.

2024-02-17 17:45 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +     * @todo Test me!
Yes due to the aforementioned UTMCoordinate assumptions. I have altered the todo message to be more specific.

2024-02-17 17:45 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.h
> +     * @todo Make Obstacle into struct for readability.
This one is not, I have removed it with the latest commit.

2024-02-17 17:46 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +        return m_vPathCoordinates;
I spaced everything out a bit - should be a bit more readable now.

2024-02-17 18:41 UTC, Byrdman32 approved these changes

2024-02-17 19:12 UTC, ClayJay3 approved these changes

2024-02-17 19:13 UTC, merged