Feature/astar
MissouriMRDT/Autonomy_Software pull request #259
Opened 2024-04-28 23:28 UTC by Kai-Shafe

Bugfixes:

- [ ] FindNearestBoundaryPoint() now properly maps outside coordinates to the proper boundary point, and now handles when the goal coordinate is inside the maximum boundary. 
- [ ] FindNearestBoundaryPoint() and RoundUTMCoordinate() now return a new UTMCoordinate struct to avoid mutating the original coordinate.
- [ ] ValidCoordinate() boundary check statement logic was incorrect, it now properly includes internal coordinates and excludes external coordinates.
- [ ] AStarNodes now contain a shared_ptr to the parent instead of a raw pointer. This allows for heap allocation and garbage collection of the node, and will guarantee pointer validity for parent nodes when dereferenced in ConstructPath(). This change is needed since the underlying memory of vClosedList is not guaranteed to be static, so I wasn't able to initialize pointers to the correct nodes and have them remain valid. This was the solution that I found this to be the simplest.
- [ ] Changed goal evaluation in PlanAvoidanceRoute() to use GeoMeasurements instead of directly comparing UTMCoordinates.

Updates:

- [ ] AvoidanceState now handles when PlanAvoidanceRoute() fails to generate a path by handling eEndObstacleAvoidance.
- [ ] Added Sharpen kernel to PreprocessFrame() in TagDetector.cpp since this change wasn't published to the Aruco branch properly.
- [ ] Changed AvoidanceState to use the TimeIntervalStuckDetector struct.
- [ ] ConstructPath() no longer uses std::reverse(), now the function uses the recursion structure of the function to make sure the path coordinate vector are placed in the correct order.
- [ ] Changed CalculateNodeHValue() to use GeoMeasurements instead of diagonal distance (This change can be reverted if the performance of PlanAvoidanceRoute() needs improvement). 
- [ ] Removed outdated Python codebase variables in AvoidanceState.

2024-04-29 01:15 UTC, ClayJay3 requested changes

2024-04-29 01:15 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +    const double AVOIDANCE_STATE_DRIVE = 1.0;    // Drive speed of avoidance state
Change name to `AVOIDANCE_STATE_MOTOR_POWER` to be consistent with other state constants.

Also please change line 302: `REVERSE_POWER` to `REVERSE_MOTOR_POWER`. (this was missed in an old PR)

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.h
>              void UTMCoordinateToString(const geoops::UTMCoordinate& stToTranslate, std::string& szTranslation);
To make this method easier to use and subsequent code cleaner, you might consider just returning a string instead of taking in a second argument. The data here is lightweight enough that it won't matter if a copy of the string is returned.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.h
>              void UpdateObstacleData(const std::vector<sl::ObjectData>& vObstacles);
Move under `Setters` section.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.h
>              void UpdateObstacleData(const std::vector<sl::ObjectData>& vObstacles);
Add an overloaded method for both UpdateObstacleData() and AddObstacle() methods that take in an AStar:Obstacle, that way we can add obstacles that don't come from the ZEDSDK.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
>      }
This function is now just a wrapper for another function. Delete this method and directly use geoops::CalculateGeoMeasurement instead.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
>              nodes::AStarNode nextParent = vOpenList.back();
nextParent does not following naming convention.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +                    geoops::UTMCoordinate successorCoordinate(nextParent.stNodeLocation);
successorCoordinate does not follow naming convention.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +                    nodes::AStarNode nextSuccessor(vClosedList.back(), successorCoordinate);
nextSuccessor does not follow naming convention.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> +        ConstructPath(*stEndNode.stdParentNode);
This might not be de-referencing the parent node in the way you think. `*stEndNode.stdParentNode` will first deref stEndNode and then access stdParentNode. If you want to deref stdParentNode change to something like `*(*stEndNode.stdParentNode)` I'm also skeptical if this method since the nodes store actual pointers but the method takes in references and the class member variables are references.

2024-04-29 01:15 UTC, ClayJay3 commented on src/algorithms/planners/AStar.cpp
> -     *
I'm commenting here because github doesn't allow comments on non-diffed lines. This comment is about the UpdateObstacleData() method. 

That method name implies that the old obstacles won't be deleted. Rename method, add note, or keep old obstacles and let the user of AStar class clear the obstacles when they want.

2024-04-29 01:15 UTC, ClayJay3 commented on src/states/AvoidanceState.cpp
> +        m_stStart        = globals::g_pWaypointHandler->SmartRetrieveRoverPose().GetUTMCoordinate();
Store the whole pose and call .GetUTMCoordinate when needed. This will make sure potentially useful data isn't discarded that might be used in the future.

2024-04-29 01:15 UTC, ClayJay3 commented on src/states/AvoidanceState.cpp
> +        std::vector<geoops::UTMCoordinate> v_clear = {};
This seems kinda hacky to me. Add a ClearPath() or ResetController() method to the StanleyController class.

2024-04-29 01:15 UTC, ClayJay3 commented on src/states/AvoidanceState.cpp
> +        geoops::RoverPose stCurrentPose                  = globals::g_pWaypointHandler->SmartRetrieveRoverPose();
From what I can tell, this currently doesn't follow the generated path by using astar and the stanleycontroller. Currently works that same as the navigating state.

2024-04-29 01:15 UTC, ClayJay3 commented on src/states/AvoidanceState.cpp
> +        }
This comment refers to the HandleEvent method.

```
case Event::eEndObstacleAvoidance:
    {
        LOG_INFO(logging::g_qSharedLogger, "AvoidanceState: Handling EndObstacleAvoidance event.");
        eNextState = States::NUM_STATES;    // Replace with `get_prev_state()`
        break;
    }
```

If this event ever gets triggered in its current code state, then the statemachine will be stuck in avoidance since the next state doesn't exist. Look at the stuck state if you want an example that shows how to return to the state that triggered avoidance.

2024-04-29 01:15 UTC, ClayJay3 commented on src/states/AvoidanceState.h
> +            controllers::StanleyController m_stController =
Do not instantiate class member objects in the header file, move to constructor.

2024-04-29 01:15 UTC, ClayJay3 commented on src/util/planners/Nodes.hpp
> +                std::shared_ptr<AStarNode> stdParentNode;    // A shared pointer to the parent node the this nodes comes after in the path.
Change name to pParentNode since this is still a pointer.

2024-04-29 01:15 UTC, ClayJay3 commented on src/vision/aruco/ArucoDetection.hpp
> +        cv::filter2D(cvInputFrame, cvInputFrame, -1, constants::ARUCO_SHARPEN_KERNEL_EXTRA);
What is the performance like on this? Just curious.

2024-04-29 01:40 UTC, ClayJay3 commented on src/vision/aruco/ArucoDetection.hpp
> +        cv::filter2D(cvInputFrame, cvInputFrame, -1, constants::ARUCO_SHARPEN_KERNEL_EXTRA);
Also change the `cvInputFrame` to `cvOutputFrame`. 

`cv::filter2D(cvOutputFrame, cvOutputFrame, -1, constants::ARUCO_SHARPEN_KERNEL_EXTRA);`

2024-04-29 04:14 UTC, Byrdman32 requested changes
Same things that Clayton noted. Also some notes on the Unit Test.

2024-04-29 04:14 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
>          short sDirection;
It would be better to not leave an uninitialized variable here.

2024-04-29 04:14 UTC, Byrdman32 commented on src/algorithms/planners/AStar.cpp
> +        if (stEndNode.stdParentNode == nullptr)
I may just be miss reading this but what does the `std` abbreviation on the var name mean?

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @copyright Copyright MRDT 2023 - All Rights Reserved
Should be copyright 2024:

` * @copyright Copyright MRDT 2024 - All Rights Reserved`

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @brief Unit test for PIDController algorithm class.
Change brief to:

` * @brief Unit test for AStar algorithm class.`

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @author ClayJay3 (claytonraycowen@gmail.com)
Change to your name and email:

` * @author Kai Shafe (kasq5m@umsystem.edu)`

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @date 2023-10-12
Change to today's date:

` * @date 2024-04-28`

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @file PIDController.cc
Change to correct file name:

` * @file AStarPlanner.cc`

2024-04-29 04:14 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> +}
Add blank line to end of file.

2024-04-29 04:17 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +        ConstructPath(*stEndNode.stdParentNode);
When I was running through the code with the debugger, this was one of the methods I thoroughly traced as it was the primary one giving me issues. When I traced it with the current implementation, it did actually dereference stdParentNode instead of stEndNode, and correctly built the path while on the sim. When I tried adding the additional dereference you mentioned I got an error.

2024-04-29 04:51 UTC, Kai-Shafe commented on src/vision/aruco/ArucoDetection.hpp
> +        cv::filter2D(cvInputFrame, cvInputFrame, -1, constants::ARUCO_SHARPEN_KERNEL_EXTRA);
It's been a while since I had tested it (and I'm not really sure how to test it now with my current setup lol), but from what I remember the ..._KERNEL_FAST dropped us to around 20-25 FPS, and the ..._KERNEL_EXTRA dropped us to about 15-20 FPS on a camera that was getting 30 FPS.

2024-04-29 05:06 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> +        if (stEndNode.stdParentNode == nullptr)
When I checked CONTRIBUTING.md, that was the stated prefix for std types, which is where I got the shared_ptr object. Originally stParentNode was misnamed as it was a pointer, and the latest push has changed the prefix to be `pParentNode`.

2024-04-29 05:12 UTC, Kai-Shafe commented on src/algorithms/planners/AStar.cpp
> -     *
UpdateObstacleData() now has a second bool param (default: true) named `bClearObstacles` that will optionally clear the obstacles vector within AStar.

2024-04-29 05:15 UTC, Kai-Shafe commented on src/states/AvoidanceState.cpp
> +        geoops::RoverPose stCurrentPose                  = globals::g_pWaypointHandler->SmartRetrieveRoverPose();
Yeah... something I missed that might invalidate a lot of my testing. I've changed AvoidanceState to call the StanleyController::Calculate() method.

2024-04-29 14:49 UTC, ClayJay3 reviewed
Looks good, functionality need to be checked via the unit test which currently segfaults. Then PR can be merged.

2024-05-03 06:33 UTC, Kai-Shafe commented
During debugging the unit test for `PlanAvoidanceRoute()` I discovered that my code would have a critical failure if the start or end `UTMCoordinate` structs were not initialized fully, which would result in a `GeoMeasurement` struct being returned with uninitialized data. I added a procedure for checking for uninitialized data, utilizing Euclidian distance on just the Easting and Northing values of two coordinates. As of right now, my code now properly returns a valid path during the unit tests.

I was wondering if there was any better way to initialize `UTMCoordinate` structs in the unit tests so I can avoid the error being logged on line 443 in GeospatialOperations.hpp? I feel as though the handling I added was a bit hack-y and isn't ideal. Any advice is appreciated!

2024-05-03 07:44 UTC, Byrdman32 commented
> During debugging the unit test for `PlanAvoidanceRoute()` I discovered that my code would have a critical failure if the start or end `UTMCoordinate` structs were not initialized fully, which would result in a `GeoMeasurement` struct being returned with uninitialized data. I added a procedure for checking for uninitialized data, and handled it by utilizing Euclidian distance on just the Easting and Northing values of two coordinates. As of right now, my code now properly returns a valid path during the unit tests.
> 
> I was wondering if there was any better way to initialize `UTMCoordinate` structs in the unit tests so I can avoid the error being logged on line 443 in GeospatialOperations.hpp? I feel as though the handling I added was a bit hack-y and isn't ideal. Any advice is appreciated!

I'll look at this in the morning.

2024-09-16 01:39 UTC, Byrdman32 approved these changes
Looks really good. Please make the minor change to the doxygen header in `AStarPlanner.cc` and it looks good to me.

2024-09-16 01:39 UTC, Byrdman32 commented on tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
> + * @copyright Copyright MRDT 2024 - All Rights Reserved
Change to `* @copyright Copyright Mars Rover Design Team 2024 - All Rights Reserved`

2024-09-16 01:51 UTC, ClayJay3 approved these changes
Nice tests.

2024-09-16 01:51 UTC, ClayJay3 commented on src/drivers/DriveBoard.cpp
> +    float fDriveBoardRightPower = numops::MapRange(float(dRightSpeed), -1.0F, 1.0F, m_fMinDriveEffort, m_fMaxDriveEffort);
Change to lower.

2024-09-16 01:51 UTC, ClayJay3 commented on src/vision/aruco/TagDetector.h
> +        void EnableTensorflowDetection(const float fMinObjectConfidence = 0.4F, const float fNMSThreshold = 0.6F);
Change to lower

2024-09-16 02:14 UTC, merged