Final Updates from URC 2024
MissouriMRDT/Autonomy_Software pull request #270
Opened 2024-08-13 20:51 UTC by Byrdman32

2024-08-13 20:55 UTC, Byrdman32 commented
All the merge of https://github.com/MissouriMRDT/Autonomy_Software/pull/270/commits/8f29db37c7752adabdc974d606179024e591a0a5 did was update who is able to approve pull requests on this repo.

2024-08-13 23:34 UTC, wiidler approved these changes

2024-08-13 23:36 UTC, merged

2024-08-13 23:55 UTC, ClayJay3 requested changes

2024-08-13 23:55 UTC, ClayJay3 commented on src/drivers/NavigationBoard.cpp
> +    return m_bNavBoardOutOfDate;
This variable also needs to be set in the other methods or else the navboard could be out of date, but the flag won't get set unless `GetGPSData()` is called. Put in all methods that also print out of date warnings.

2024-08-13 23:55 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.cpp
Don't need this, we might still want to subscribe that way we can have the cell voltages in the log.

2024-08-13 23:55 UTC, ClayJay3 commented on src/handlers/StateMachineHandler.h
> +                constants::BATTERY_CHECKS_ENABLED)
Move the `constants::BATTERY_CHECKS_ENABLED` to be the first thing the conditional checks to avoid making a call to the state machine handler when checks are disabled.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/ApproachingMarkerState.cpp
> +                 constants::APPROACH_MARKER_PROXIMITY_THRESHOLD);
Is this supposed to be a debug now? This will flood the console since it's in the run method, we don't want to do that as it makes reading the console more difficult. Consider making this debug or put it somewhere where it gets printed out occasionally.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/IdleState.cpp
> +
This is currently ran every iteration through the run. This will flood the console, make this print out every 5 or 10 seconds.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/IdleState.cpp
> +
or remove it

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/NavigatingState.cpp
> +
I'm cool with leaving this in, but we don't want to flood the console, make this print every 5 or 10 seconds.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/VerifyingPositionState.cpp
> +                network::g_pRoveCommUDPNode->SendUDPPacket(stPacket, "0.0.0.0", constants::ROVECOMM_OUTGOING_UDP_PORT);
Move this to the reached goal case in the MultimediaBoard driver.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/VerifyingObjectState.cpp
> +                network::g_pRoveCommUDPNode->SendUDPPacket(stPacket, "0.0.0.0", constants::ROVECOMM_OUTGOING_UDP_PORT);
Move this to the multimedia board so we don't have to copy paste this everywhere.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/VerifyingObjectState.cpp
> +
Missing a SendLightingBoard state here.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/VerifyingMarkerState.cpp
> +                network::g_pRoveCommUDPNode->SendUDPPacket(stPacket, "0.0.0.0", constants::ROVECOMM_OUTGOING_UDP_PORT);
Move to multimedia board.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/VerifyingMarkerState.cpp
> +
Missing a send lighting state here.

2024-08-13 23:55 UTC, ClayJay3 commented on src/states/ApproachingMarkerState.cpp
> +                network::g_pRoveCommUDPNode->SendUDPPacket(stPacket, "0.0.0.0", constants::ROVECOMM_OUTGOING_UDP_PORT);
Move to multimediaboard::sendlightingstate

2024-08-14 00:02 UTC, Byrdman32 commented on src/states/IdleState.cpp
> +
I'd be fine with this being deleted.

2024-08-14 00:03 UTC, Byrdman32 commented on src/states/ApproachingMarkerState.cpp
> +                 constants::APPROACH_MARKER_PROXIMITY_THRESHOLD);
This can be changed to debug and possible limited in how often it prints.