Topic/multithreading infrastructure
MissouriMRDT/Autonomy_Software pull request #58
Opened 2023-07-27 01:47 UTC by ClayJay3

#### This PR implements an interface class that aims to give programmer the ability to easily multi-thread their code without worrying about low-level thread and memory management.  Just inherit the base class and implement a couple pure virtual functions.

Since resource access management (resource locking) for the users implemented code can not be controlled internally by the interface, users should know when and how to acquire locks with mutexes and they should also use atomic whenever possible. A guide detailing this will be implemented shortly.

    - Implemented AutonomyThread bass class.
        - High level thread management
        - All threaded code implemented in pure virtual functions
        - Thread pool functionality
        - Loop parallelizer functionality
        - Guaranteed safe shutdown of threads
        - Ability to return templated type from thread pool
    - Added two threading examples
        -   A prime number calculator
        -  An Aruco tag generator

Closes issue #29

2023-07-27 02:27 UTC, Byrdman32 requested changes
Overall looks good. Please look at the comments and modify or justify the method/reason for doing it the way implemented.

2023-07-27 02:27 UTC, Byrdman32 commented on CMakeLists.txt
> +file(GLOB Tests_SRC			 	CONFIGURE_DEPENDS  "tests/*.cpp")
Go ahead and remove the search for tests here. Since it is only used in the unit section farther down.

2023-07-27 02:27 UTC, Byrdman32 commented on CMakeLists.txt
> +								 ${Tests_SRC}
And remove tests here too.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> + * @brief This example uses the opencv TagGenerator.hpp example and multithreads
Change `opencv` to `OpenCV`

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +/******************************************************************************
This needs to be a Doxygen comment block.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +            // for (int i = 0; i < m_nNumTagsToGenerate; ++i)
Why is this code still here? Is it to show an example of Non-Parallelized? 

I don't think it is needed since it appears in `ArucoGenerateTagsLinear` class below.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +/******************************************************************************
Doxygen comment block needed.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +int RunExample()
Maybe change to from `RunExample()` to `RunArucoExample()`.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
> +#include <iostream>
Add blank line before includes.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +#include <chrono>
Add blank line before includes.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
> +class PrimeCalculatorThread : public AutonomyThread<void>
Add Doxygen block comment.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +        std::mutex m_muDictMutex;    // This mutex is used for locking write access to the dictionary in threads.
Add `mu` to [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md)

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +    auto startTime = std::chrono::high_resolution_clock::now();
Change variable name to match naming convention found in [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md)

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +    auto endTime = std::chrono::high_resolution_clock::now();
Change variable name to fit with [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md) naming conventions.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +    auto singleThreadedDuration = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime).count();
Same as above.

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +    auto multiThreadedDuration = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime).count();
Change to work with [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md)

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
> +        bool isPrime(int& nNum)
Change to Pascal Case as noted in [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md)

2023-07-27 02:27 UTC, Byrdman32 commented on examples/threading/PrimeNumbers.hpp
> +        void calculatePrimes(int& nCount)
Change to Pascal Case as noted in [CONTRIBUTING.md](https://github.com/MissouriMRDT/Autonomy_Software/blob/development/CONTRIBUTING.md)

2023-07-27 02:27 UTC, Byrdman32 commented on src/interfaces/README.md
> +<<<<<<< HEAD
Needs to have garbage from merge removed.

2023-07-27 02:27 UTC, Byrdman32 commented on src/interfaces/README.md
> +<<<<<<< HEAD
Needs to have garbage from merge removed.

2023-07-28 01:18 UTC, ClayJay3 commented on examples/threading/ArucoGenerateTags.hpp
> +            // for (int i = 0; i < m_nNumTagsToGenerate; ++i)
I left it there as an easy way for whoever is viewing the sample to see the speed different between the two. I'll redo the comments so that is more obvious.

2023-07-28 02:55 UTC, ClayJay3 commented on examples/threading/ArucoGenerateTags.hpp
> +int RunExample()
I was experimenting with having each example contain a function with the same RunExample method. Then use the C++ preprocessor toggle whether or not to run in example mode or normal mode. I pushed those changes to the auto-example-runner branch.

2023-07-28 02:59 UTC, ClayJay3 commented on src/interfaces/README.md
> +<<<<<<< HEAD
Whoops

2023-07-28 03:00 UTC, ClayJay3 reviewed
All comments resolved, and requested changes have been made.

2023-07-28 03:56 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +            // for (int i = 0; i < m_nNumTagsToGenerate; ++i)
Sounds good.

2023-07-28 03:57 UTC, Byrdman32 commented on examples/threading/ArucoGenerateTags.hpp
> +int RunExample()
Sounds good. I'll look at it.

2023-07-28 04:03 UTC, Byrdman32 requested changes
Making the one change requested in the devcontainer.json file and then it looks like it will be ready for merging.

2023-07-28 04:03 UTC, Byrdman32 commented on .devcontainer/devcontainer.json
This needs to be set to use the `ghcr.io/missourimrdt/autonomy-ubuntu` image every time we merge into development. That way people don't pull and have it start automatically rebuilding the image.

2023-07-29 03:02 UTC, Byrdman32 requested changes

2023-07-29 03:02 UTC, Byrdman32 commented on data/ASCII/README.md
Need to change top of README.md to be `\dir data/ASCII` instead of `\dir src/util/ASCII`

2023-07-29 03:35 UTC, Byrdman32 approved these changes
Looks great! Thanks for your patience.

2023-07-29 03:54 UTC, merged