Initial State Machine Implementation
MissouriMRDT/Autonomy_Software pull request #66
Opened 2023-07-31 02:21 UTC by Byrdman32

Initial work for implementing a state machine into Autonomy. Future Pull Requests will implement the processes that happen within each state and implement the RoveComm handlers that will have the ability to start and stop the state machine.

Associated with #10

2023-07-31 03:02 UTC, ClayJay3 reviewed
All state files need doxygen comment blocks for every struct.

2023-07-31 03:02 UTC, ClayJay3 commented on CMakeLists.txt
> +                                 ${Drivers_SRC}
Drivers_SRC is provided twice.

2023-07-31 03:02 UTC, ClayJay3 commented on src/AutonomyConstants.h
> +// Drive Constants
This should be in a namespace so we can do typedefs.

namespace constants
{
    // Drive constants.
    const int MAX_DRIVE_POWER = 250;
    const int MIN_DRIVE_POWER = 50;
}    // namespace constants

2023-07-31 03:02 UTC, ClayJay3 commented on src/interfaces/StateMachine.hpp
> +#include "../states/IdleState.hpp"
Why are the state transitions redeclared here and then defined when included? All #includes should be at the top of the file and then struct objects should be declared. There might be a more elegant way to do these state transitions.

2023-07-31 03:11 UTC, Byrdman32 commented on src/interfaces/StateMachine.hpp
> +#include "../states/IdleState.hpp"
> Why are the state transitions redeclared here and then defined when included? All #includes should be at the top of the file and then struct objects should be declared. There might be a more elegant way to do these state transitions.

The states have to be declared after the state machine object is declared. This was the cleanest way I have come up with but am open to suggestions.

2023-08-01 00:52 UTC, ClayJay3 requested changes
All structs should have simple doxygen comment blocks.

2023-08-01 02:33 UTC, ClayJay3 approved these changes

2023-08-01 02:43 UTC, merged