Multithreading Interface Documentation
MissouriMRDT/Autonomy_Software pull request #90
Opened 2023-08-15 17:28 UTC by ClayJay3

### Threading Docs
Added a detailed guide on how developers should use the `AutonomyThread` interface. It goes over how to actually inherit the class and implement the pure virtual functions, as well as some basics on how resources should be handled with mutexes, locks, and atomics.

README is in the `src/threads` folder.

2023-08-15 17:33 UTC, Byrdman32 commented
Added Jesse as a reviewer since the Drone Autonomy Code will be based off of Autonomy_Software - Sprint 0

2023-08-15 19:06 UTC, Byrdman32 requested changes

2023-08-15 19:06 UTC, Byrdman32 commented on src/threads/README.md
> +Create a new file in the `threads` directory and name it appropriately. For example, if there is a main class responsible for managing the states of the rover, create a file named `StateMachineThread
VisionThread.py ???

I thought that we were switching Autonomy from Python to C++.

2023-08-15 19:09 UTC, Byrdman32 commented
Also, make sure to merge development now that the #89 has been merged.

2023-08-15 19:24 UTC, ClayJay3 commented on src/threads/README.md
> +Create a new file in the `threads` directory and name it appropriately. For example, if there is a main class responsible for managing the states of the rover, create a file named `StateMachineThread
fixed VisionThread.py

2023-08-15 19:43 UTC, Byrdman32 approved these changes
Approved

2023-08-17 01:16 UTC, Byrdman32 commented
@ClayJay3 Donovan says that it looks good and approves the PR.

2023-08-17 02:54 UTC, Byrdman32 commented
@ClayJay3 Jesse says that it looks good and approves the PR.

2023-08-17 02:55 UTC, ClayJay3 commented
Why don't they just approve it?

2023-08-17 02:56 UTC, jessedeuel commented
I don't have the correct permissions. Eli is gonna fix it tomorrow.

2023-08-17 02:57 UTC, Byrdman32 commented
Because GitHub is being stupid. It wasn't letting Jesse approve it. And Donovan didn't have access to his computer when he reviewed it and asked me to mark it for him.

2023-08-18 00:17 UTC, wiidler reviewed
Looks awesome, sorry for the delay in getting a review in

2023-08-18 00:17 UTC, wiidler commented on src/threads/README.md
> -For example, if there is a main class responsible for managing the states of the rover, create a file named `StateMachineThread.cpp`. Similarly, if there is a main class handling vision processing, n
should it be VisionThread.cpp? just want to make sure it doesn't confuse people since we switched to C++

2023-08-18 00:29 UTC, ClayJay3 commented on src/threads/README.md
> -For example, if there is a main class responsible for managing the states of the rover, create a file named `StateMachineThread.cpp`. Similarly, if there is a main class handling vision processing, n
Yeah, I fixed it in a new commit, this is the old side.

2023-08-18 00:32 UTC, wiidler approved these changes

2023-08-18 00:34 UTC, merged